# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41d6e7c9a3d9e5c4266e6b28a015a70967d50dd79151d434593d97864aa373f86df9fd0ce6ed87147a30f31230c5b0586cd5e05a9a01a37e27b96751bf38cef1

test:
  secret_key_base: 87f981fd39efed124aa1eb16e263914b47f6f17372f4c5d443c4aece42871deff382304355544894c7496244c68e64a457c56688e8b8861abba84f0e5c747a91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
